parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony_main
    database_user: root
    database_password: vunnu07
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: a65361cc40acd4f0fb87e27aadb3e7a7995192f5
    database_path: null
